[Thu Nov 28 12:15:40.341557 2024] [php:error] [pid 11472:tid 1880] [client 127.0.0.1:63581] PHP Parse error:  syntax error, unexpected single-quoted string "basePath", expecting "]" in C:\\xampp\\htdocs\\it.uz\\frontend\\config\\main.php on line 12, referer: http://it.uz/frontend/web/index.php?r=site%2Fabout
[Thu Dec 19 19:37:38.953369 2024] [php:error] [pid 5764:tid 1840] [client 127.0.0.1:50085] PHP Parse error:  syntax error, unexpected single-quoted string "language", expecting "]" in C:\\xampp\\htdocs\\it.uz\\frontend\\config\\main.php on line 12
[Thu Dec 19 19:37:40.446166 2024] [php:error] [pid 5764:tid 1848] [client 127.0.0.1:50089] PHP Parse error:  syntax error, unexpected single-quoted string "language", expecting "]" in C:\\xampp\\htdocs\\it.uz\\frontend\\config\\main.php on line 12, referer: http://sanat.uz/frontend/web/index.php?r=site%2Fsignup
[Thu Dec 19 22:26:48.029290 2024] [php:notice] [pid 5764:tid 1832] [client 127.0.0.1:62129] An Error occurred while handling another error:\nyii\\base\\UnknownPropertyException: Getting unknown property: common\\models\\User::isAdmin in C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Component.php:154\nStack trace:\n#0 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\db\\BaseActiveRecord.php(296): yii\\base\\Component->__get('isAdmin')\n#1 C:\\xampp\\htdocs\\it.uz\\frontend\\views\\layouts\\main.php(47): yii\\db\\BaseActiveRecord->__get('isAdmin')\n#2 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\View.php(348): require('C:\\\\xampp\\\\htdocs...')\n#3 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\View.php(258): yii\\base\\View->renderPhpFile('C:\\\\xampp\\\\htdocs...', Array)\n#4 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Controller.php(422): yii\\base\\View->renderFile('C:\\\\xampp\\\\htdocs...', Array, Object(frontend\\controllers\\SiteController))\n#5 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Controller.php(408): yii\\base\\Controller->renderContent('<div class="sit...')\n#6 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\web\\ErrorAction.php(139): yii\\base\\Controller->render('error', Array)\n#7 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\web\\ErrorAction.php(118): yii\\web\\ErrorAction->renderHtmlResponse()\n#8 [internal function]: yii\\web\\ErrorAction->run()\n#9 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Action.php(93): call_user_func_array(Array, Array)\n#10 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Controller.php(178): yii\\base\\Action->runWithParams(Array)\n#11 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Module.php(552): yii\\base\\Controller->runAction('error', Array)\n#12 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\web\\ErrorHandler.php(109): yii\\base\\Module->runAction('site/error')\n#13 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\ErrorHandler.php(152): yii\\web\\ErrorHandler->renderException(Object(yii\\base\\UnknownPropertyException))\n#14 [internal function]: yii\\base\\ErrorHandler->handleException(Object(yii\\base\\UnknownPropertyException))\n#15 {main}\nPrevious exception:\nyii\\base\\UnknownPropertyException: Getting unknown property: common\\models\\User::isAdmin in C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Component.php:154\nStack trace:\n#0 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\db\\BaseActiveRecord.php(296): yii\\base\\Component->__get('isAdmin')\n#1 C:\\xampp\\htdocs\\it.uz\\frontend\\views\\layouts\\main.php(47): yii\\db\\BaseActiveRecord->__get('isAdmin')\n#2 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\View.php(348): require('C:\\\\xampp\\\\htdocs...')\n#3 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\View.php(258): yii\\base\\View->renderPhpFile('C:\\\\xampp\\\\htdocs...', Array)\n#4 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Controller.php(422): yii\\base\\View->renderFile('C:\\\\xampp\\\\htdocs...', Array, Object(frontend\\controllers\\SiteController))\n#5 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Controller.php(408): yii\\base\\Controller->renderContent('<div class="sit...')\n#6 C:\\xampp\\htdocs\\it.uz\\frontend\\controllers\\SiteController.php(134): yii\\base\\Controller->render('contact', Array)\n#7 [internal function]: frontend\\controllers\\SiteController->actionContact()\n#8 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\InlineAction.php(57): call_user_func_array(Array, Array)\n#9 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Controller.php(178): yii\\base\\InlineAction->runWithParams(Array)\n#10 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Module.php(552): yii\\base\\Controller->runAction('contact', Array)\n#11 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\web\\Application.php(103): yii\\base\\Module->runAction('site/contact', Array)\n#12 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Application.php(384): yii\\web\\Application->handleRequest(Object(yii\\web\\Request))\n#13 C:\\xampp\\htdocs\\it.uz\\frontend\\web\\index.php(18): yii\\base\\Application->run()\n#14 {main}, referer: http://it.uz/frontend/web/index.php?r=site%2Fabout
[Thu Dec 19 22:26:51.822533 2024] [php:notice] [pid 5764:tid 1848] [client 127.0.0.1:62131] An Error occurred while handling another error:\nyii\\base\\UnknownPropertyException: Getting unknown property: common\\models\\User::isAdmin in C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Component.php:154\nStack trace:\n#0 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\db\\BaseActiveRecord.php(296): yii\\base\\Component->__get('isAdmin')\n#1 C:\\xampp\\htdocs\\it.uz\\frontend\\views\\layouts\\main.php(47): yii\\db\\BaseActiveRecord->__get('isAdmin')\n#2 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\View.php(348): require('C:\\\\xampp\\\\htdocs...')\n#3 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\View.php(258): yii\\base\\View->renderPhpFile('C:\\\\xampp\\\\htdocs...', Array)\n#4 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Controller.php(422): yii\\base\\View->renderFile('C:\\\\xampp\\\\htdocs...', Array, Object(frontend\\controllers\\SiteController))\n#5 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Controller.php(408): yii\\base\\Controller->renderContent('<div class="sit...')\n#6 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\web\\ErrorAction.php(139): yii\\base\\Controller->render('error', Array)\n#7 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\web\\ErrorAction.php(118): yii\\web\\ErrorAction->renderHtmlResponse()\n#8 [internal function]: yii\\web\\ErrorAction->run()\n#9 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Action.php(93): call_user_func_array(Array, Array)\n#10 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Controller.php(178): yii\\base\\Action->runWithParams(Array)\n#11 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Module.php(552): yii\\base\\Controller->runAction('error', Array)\n#12 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\web\\ErrorHandler.php(109): yii\\base\\Module->runAction('site/error')\n#13 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\ErrorHandler.php(152): yii\\web\\ErrorHandler->renderException(Object(yii\\base\\UnknownPropertyException))\n#14 [internal function]: yii\\base\\ErrorHandler->handleException(Object(yii\\base\\UnknownPropertyException))\n#15 {main}\nPrevious exception:\nyii\\base\\UnknownPropertyException: Getting unknown property: common\\models\\User::isAdmin in C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Component.php:154\nStack trace:\n#0 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\db\\BaseActiveRecord.php(296): yii\\base\\Component->__get('isAdmin')\n#1 C:\\xampp\\htdocs\\it.uz\\frontend\\views\\layouts\\main.php(47): yii\\db\\BaseActiveRecord->__get('isAdmin')\n#2 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\View.php(348): require('C:\\\\xampp\\\\htdocs...')\n#3 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\View.php(258): yii\\base\\View->renderPhpFile('C:\\\\xampp\\\\htdocs...', Array)\n#4 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Controller.php(422): yii\\base\\View->renderFile('C:\\\\xampp\\\\htdocs...', Array, Object(frontend\\controllers\\SiteController))\n#5 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Controller.php(408): yii\\base\\Controller->renderContent('<div class="sit...')\n#6 C:\\xampp\\htdocs\\it.uz\\frontend\\controllers\\SiteController.php(78): yii\\base\\Controller->render('index')\n#7 [internal function]: frontend\\controllers\\SiteController->actionIndex()\n#8 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\InlineAction.php(57): call_user_func_array(Array, Array)\n#9 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Controller.php(178): yii\\base\\InlineAction->runWithParams(Array)\n#10 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Module.php(552): yii\\base\\Controller->runAction('', Array)\n#11 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\web\\Application.php(103): yii\\base\\Module->runAction('', Array)\n#12 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Application.php(384): yii\\web\\Application->handleRequest(Object(yii\\web\\Request))\n#13 C:\\xampp\\htdocs\\it.uz\\frontend\\web\\index.php(18): yii\\base\\Application->run()\n#14 {main}
[Thu Dec 19 22:26:52.304496 2024] [php:notice] [pid 5764:tid 1848] [client 127.0.0.1:62142] An Error occurred while handling another error:\nyii\\base\\UnknownPropertyException: Getting unknown property: common\\models\\User::isAdmin in C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Component.php:154\nStack trace:\n#0 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\db\\BaseActiveRecord.php(296): yii\\base\\Component->__get('isAdmin')\n#1 C:\\xampp\\htdocs\\it.uz\\frontend\\views\\layouts\\main.php(47): yii\\db\\BaseActiveRecord->__get('isAdmin')\n#2 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\View.php(348): require('C:\\\\xampp\\\\htdocs...')\n#3 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\View.php(258): yii\\base\\View->renderPhpFile('C:\\\\xampp\\\\htdocs...', Array)\n#4 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Controller.php(422): yii\\base\\View->renderFile('C:\\\\xampp\\\\htdocs...', Array, Object(frontend\\controllers\\SiteController))\n#5 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Controller.php(408): yii\\base\\Controller->renderContent('<div class="sit...')\n#6 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\web\\ErrorAction.php(139): yii\\base\\Controller->render('error', Array)\n#7 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\web\\ErrorAction.php(118): yii\\web\\ErrorAction->renderHtmlResponse()\n#8 [internal function]: yii\\web\\ErrorAction->run()\n#9 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Action.php(93): call_user_func_array(Array, Array)\n#10 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Controller.php(178): yii\\base\\Action->runWithParams(Array)\n#11 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Module.php(552): yii\\base\\Controller->runAction('error', Array)\n#12 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\web\\ErrorHandler.php(109): yii\\base\\Module->runAction('site/error')\n#13 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\ErrorHandler.php(152): yii\\web\\ErrorHandler->renderException(Object(yii\\base\\UnknownPropertyException))\n#14 [internal function]: yii\\base\\ErrorHandler->handleException(Object(yii\\base\\UnknownPropertyException))\n#15 {main}\nPrevious exception:\nyii\\base\\UnknownPropertyException: Getting unknown property: common\\models\\User::isAdmin in C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Component.php:154\nStack trace:\n#0 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\db\\BaseActiveRecord.php(296): yii\\base\\Component->__get('isAdmin')\n#1 C:\\xampp\\htdocs\\it.uz\\frontend\\views\\layouts\\main.php(47): yii\\db\\BaseActiveRecord->__get('isAdmin')\n#2 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\View.php(348): require('C:\\\\xampp\\\\htdocs...')\n#3 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\View.php(258): yii\\base\\View->renderPhpFile('C:\\\\xampp\\\\htdocs...', Array)\n#4 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Controller.php(422): yii\\base\\View->renderFile('C:\\\\xampp\\\\htdocs...', Array, Object(frontend\\controllers\\SiteController))\n#5 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Controller.php(408): yii\\base\\Controller->renderContent('<div class="sit...')\n#6 C:\\xampp\\htdocs\\it.uz\\frontend\\controllers\\SiteController.php(78): yii\\base\\Controller->render('index')\n#7 [internal function]: frontend\\controllers\\SiteController->actionIndex()\n#8 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\InlineAction.php(57): call_user_func_array(Array, Array)\n#9 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Controller.php(178): yii\\base\\InlineAction->runWithParams(Array)\n#10 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Module.php(552): yii\\base\\Controller->runAction('', Array)\n#11 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\web\\Application.php(103): yii\\base\\Module->runAction('', Array)\n#12 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Application.php(384): yii\\web\\Application->handleRequest(Object(yii\\web\\Request))\n#13 C:\\xampp\\htdocs\\it.uz\\frontend\\web\\index.php(18): yii\\base\\Application->run()\n#14 {main}
[Thu Dec 19 22:29:08.850925 2024] [php:notice] [pid 5764:tid 1832] [client 127.0.0.1:62556] An Error occurred while handling another error:\nyii\\base\\UnknownPropertyException: Getting unknown property: common\\models\\User::isAdmin in C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Component.php:154\nStack trace:\n#0 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\db\\BaseActiveRecord.php(296): yii\\base\\Component->__get('isAdmin')\n#1 C:\\xampp\\htdocs\\it.uz\\frontend\\views\\layouts\\main.php(47): yii\\db\\BaseActiveRecord->__get('isAdmin')\n#2 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\View.php(348): require('C:\\\\xampp\\\\htdocs...')\n#3 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\View.php(258): yii\\base\\View->renderPhpFile('C:\\\\xampp\\\\htdocs...', Array)\n#4 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Controller.php(422): yii\\base\\View->renderFile('C:\\\\xampp\\\\htdocs...', Array, Object(frontend\\controllers\\SiteController))\n#5 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Controller.php(408): yii\\base\\Controller->renderContent('<div class="sit...')\n#6 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\web\\ErrorAction.php(139): yii\\base\\Controller->render('error', Array)\n#7 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\web\\ErrorAction.php(118): yii\\web\\ErrorAction->renderHtmlResponse()\n#8 [internal function]: yii\\web\\ErrorAction->run()\n#9 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Action.php(93): call_user_func_array(Array, Array)\n#10 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Controller.php(178): yii\\base\\Action->runWithParams(Array)\n#11 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Module.php(552): yii\\base\\Controller->runAction('error', Array)\n#12 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\web\\ErrorHandler.php(109): yii\\base\\Module->runAction('site/error')\n#13 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\ErrorHandler.php(152): yii\\web\\ErrorHandler->renderException(Object(yii\\base\\UnknownPropertyException))\n#14 [internal function]: yii\\base\\ErrorHandler->handleException(Object(yii\\base\\UnknownPropertyException))\n#15 {main}\nPrevious exception:\nyii\\base\\UnknownPropertyException: Getting unknown property: common\\models\\User::isAdmin in C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Component.php:154\nStack trace:\n#0 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\db\\BaseActiveRecord.php(296): yii\\base\\Component->__get('isAdmin')\n#1 C:\\xampp\\htdocs\\it.uz\\frontend\\views\\layouts\\main.php(47): yii\\db\\BaseActiveRecord->__get('isAdmin')\n#2 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\View.php(348): require('C:\\\\xampp\\\\htdocs...')\n#3 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\View.php(258): yii\\base\\View->renderPhpFile('C:\\\\xampp\\\\htdocs...', Array)\n#4 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Controller.php(422): yii\\base\\View->renderFile('C:\\\\xampp\\\\htdocs...', Array, Object(frontend\\controllers\\SiteController))\n#5 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Controller.php(408): yii\\base\\Controller->renderContent('<div class="sit...')\n#6 C:\\xampp\\htdocs\\it.uz\\frontend\\controllers\\SiteController.php(78): yii\\base\\Controller->render('index')\n#7 [internal function]: frontend\\controllers\\SiteController->actionIndex()\n#8 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\InlineAction.php(57): call_user_func_array(Array, Array)\n#9 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Controller.php(178): yii\\base\\InlineAction->runWithParams(Array)\n#10 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Module.php(552): yii\\base\\Controller->runAction('', Array)\n#11 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\web\\Application.php(103): yii\\base\\Module->runAction('', Array)\n#12 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Application.php(384): yii\\web\\Application->handleRequest(Object(yii\\web\\Request))\n#13 C:\\xampp\\htdocs\\it.uz\\frontend\\web\\index.php(18): yii\\base\\Application->run()\n#14 {main}
[Thu Dec 19 22:30:05.550698 2024] [php:notice] [pid 5764:tid 1832] [client 127.0.0.1:62620] An Error occurred while handling another error:\nyii\\base\\UnknownPropertyException: Getting unknown property: common\\models\\User::isAdmin in C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Component.php:154\nStack trace:\n#0 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\db\\BaseActiveRecord.php(296): yii\\base\\Component->__get('isAdmin')\n#1 C:\\xampp\\htdocs\\it.uz\\frontend\\views\\layouts\\main.php(47): yii\\db\\BaseActiveRecord->__get('isAdmin')\n#2 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\View.php(348): require('C:\\\\xampp\\\\htdocs...')\n#3 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\View.php(258): yii\\base\\View->renderPhpFile('C:\\\\xampp\\\\htdocs...', Array)\n#4 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Controller.php(422): yii\\base\\View->renderFile('C:\\\\xampp\\\\htdocs...', Array, Object(frontend\\controllers\\SiteController))\n#5 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Controller.php(408): yii\\base\\Controller->renderContent('<div class="sit...')\n#6 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\web\\ErrorAction.php(139): yii\\base\\Controller->render('error', Array)\n#7 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\web\\ErrorAction.php(118): yii\\web\\ErrorAction->renderHtmlResponse()\n#8 [internal function]: yii\\web\\ErrorAction->run()\n#9 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Action.php(93): call_user_func_array(Array, Array)\n#10 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Controller.php(178): yii\\base\\Action->runWithParams(Array)\n#11 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Module.php(552): yii\\base\\Controller->runAction('error', Array)\n#12 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\web\\ErrorHandler.php(109): yii\\base\\Module->runAction('site/error')\n#13 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\ErrorHandler.php(152): yii\\web\\ErrorHandler->renderException(Object(yii\\base\\UnknownPropertyException))\n#14 [internal function]: yii\\base\\ErrorHandler->handleException(Object(yii\\base\\UnknownPropertyException))\n#15 {main}\nPrevious exception:\nyii\\base\\UnknownPropertyException: Getting unknown property: common\\models\\User::isAdmin in C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Component.php:154\nStack trace:\n#0 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\db\\BaseActiveRecord.php(296): yii\\base\\Component->__get('isAdmin')\n#1 C:\\xampp\\htdocs\\it.uz\\frontend\\views\\layouts\\main.php(47): yii\\db\\BaseActiveRecord->__get('isAdmin')\n#2 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\View.php(348): require('C:\\\\xampp\\\\htdocs...')\n#3 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\View.php(258): yii\\base\\View->renderPhpFile('C:\\\\xampp\\\\htdocs...', Array)\n#4 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Controller.php(422): yii\\base\\View->renderFile('C:\\\\xampp\\\\htdocs...', Array, Object(frontend\\controllers\\SiteController))\n#5 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Controller.php(408): yii\\base\\Controller->renderContent('<div class="sit...')\n#6 C:\\xampp\\htdocs\\it.uz\\frontend\\controllers\\SiteController.php(78): yii\\base\\Controller->render('index')\n#7 [internal function]: frontend\\controllers\\SiteController->actionIndex()\n#8 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\InlineAction.php(57): call_user_func_array(Array, Array)\n#9 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Controller.php(178): yii\\base\\InlineAction->runWithParams(Array)\n#10 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Module.php(552): yii\\base\\Controller->runAction('', Array)\n#11 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\web\\Application.php(103): yii\\base\\Module->runAction('', Array)\n#12 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Application.php(384): yii\\web\\Application->handleRequest(Object(yii\\web\\Request))\n#13 C:\\xampp\\htdocs\\it.uz\\frontend\\web\\index.php(18): yii\\base\\Application->run()\n#14 {main}, referer: http://it.uz/frontend/web/index.php?r=site%2Fcontact
[Thu Dec 19 22:31:54.460935 2024] [php:notice] [pid 5764:tid 1848] [client 127.0.0.1:62898] An Error occurred while handling another error:\nyii\\base\\InvalidConfigException: Unknown component ID: view in C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php:139\nStack trace:\n#0 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Module.php(766): yii\\di\\ServiceLocator->get('view', true)\n#1 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Application.php(560): yii\\base\\Module->get('view')\n#2 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Component.php(139): yii\\base\\Application->getView()\n#3 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php(77): yii\\base\\Component->__get('view')\n#4 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\web\\ErrorHandler.php(108): yii\\di\\ServiceLocator->__get('view')\n#5 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\ErrorHandler.php(152): yii\\web\\ErrorHandler->renderException(Object(yii\\base\\InvalidConfigException))\n#6 [internal function]: yii\\base\\ErrorHandler->handleException(Object(yii\\base\\InvalidConfigException))\n#7 {main}\nPrevious exception:\nyii\\base\\InvalidConfigException: The configuration for the "params" component must contain a "class" element. in C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php:209\nStack trace:\n#0 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php(265): yii\\di\\ServiceLocator->set('params', Array)\n#1 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Component.php(180): yii\\di\\ServiceLocator->setComponents(Array)\n#2 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\BaseYii.php(557): yii\\base\\Component->__set('components', Array)\n#3 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\BaseObject.php(107): yii\\BaseYii::configure(Object(yii\\web\\Application), Array)\n#4 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Application.php(204): yii\\base\\BaseObject->__construct(Array)\n#5 C:\\xampp\\htdocs\\it.uz\\frontend\\web\\index.php(18): yii\\base\\Application->__construct(Array)\n#6 {main}, referer: http://it.uz/frontend/web/index.php?r=site%2Fcontact
[Thu Dec 19 22:31:55.836220 2024] [php:notice] [pid 5764:tid 1832] [client 127.0.0.1:62899] An Error occurred while handling another error:\nyii\\base\\InvalidConfigException: Unknown component ID: view in C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php:139\nStack trace:\n#0 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Module.php(766): yii\\di\\ServiceLocator->get('view', true)\n#1 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Application.php(560): yii\\base\\Module->get('view')\n#2 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Component.php(139): yii\\base\\Application->getView()\n#3 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php(77): yii\\base\\Component->__get('view')\n#4 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\web\\ErrorHandler.php(108): yii\\di\\ServiceLocator->__get('view')\n#5 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\ErrorHandler.php(152): yii\\web\\ErrorHandler->renderException(Object(yii\\base\\InvalidConfigException))\n#6 [internal function]: yii\\base\\ErrorHandler->handleException(Object(yii\\base\\InvalidConfigException))\n#7 {main}\nPrevious exception:\nyii\\base\\InvalidConfigException: The configuration for the "params" component must contain a "class" element. in C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php:209\nStack trace:\n#0 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php(265): yii\\di\\ServiceLocator->set('params', Array)\n#1 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Component.php(180): yii\\di\\ServiceLocator->setComponents(Array)\n#2 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\BaseYii.php(557): yii\\base\\Component->__set('components', Array)\n#3 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\BaseObject.php(107): yii\\BaseYii::configure(Object(yii\\web\\Application), Array)\n#4 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Application.php(204): yii\\base\\BaseObject->__construct(Array)\n#5 C:\\xampp\\htdocs\\it.uz\\frontend\\web\\index.php(18): yii\\base\\Application->__construct(Array)\n#6 {main}
[Thu Dec 19 22:32:06.459668 2024] [php:notice] [pid 5764:tid 1848] [client 127.0.0.1:62902] An Error occurred while handling another error:\nyii\\base\\InvalidConfigException: Unknown component ID: view in C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php:139\nStack trace:\n#0 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Module.php(766): yii\\di\\ServiceLocator->get('view', true)\n#1 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Application.php(560): yii\\base\\Module->get('view')\n#2 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Component.php(139): yii\\base\\Application->getView()\n#3 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php(77): yii\\base\\Component->__get('view')\n#4 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\web\\ErrorHandler.php(108): yii\\di\\ServiceLocator->__get('view')\n#5 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\ErrorHandler.php(152): yii\\web\\ErrorHandler->renderException(Object(yii\\base\\InvalidConfigException))\n#6 [internal function]: yii\\base\\ErrorHandler->handleException(Object(yii\\base\\InvalidConfigException))\n#7 {main}\nPrevious exception:\nyii\\base\\InvalidConfigException: The configuration for the "params" component must contain a "class" element. in C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php:209\nStack trace:\n#0 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php(265): yii\\di\\ServiceLocator->set('params', Array)\n#1 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Component.php(180): yii\\di\\ServiceLocator->setComponents(Array)\n#2 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\BaseYii.php(557): yii\\base\\Component->__set('components', Array)\n#3 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\BaseObject.php(107): yii\\BaseYii::configure(Object(yii\\web\\Application), Array)\n#4 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Application.php(204): yii\\base\\BaseObject->__construct(Array)\n#5 C:\\xampp\\htdocs\\it.uz\\frontend\\web\\index.php(18): yii\\base\\Application->__construct(Array)\n#6 {main}, referer: http://it.uz/frontend/web/index.php?r=site%2Fcontact
[Thu Dec 19 22:32:07.696183 2024] [php:notice] [pid 5764:tid 1832] [client 127.0.0.1:62934] An Error occurred while handling another error:\nyii\\base\\InvalidConfigException: Unknown component ID: view in C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php:139\nStack trace:\n#0 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Module.php(766): yii\\di\\ServiceLocator->get('view', true)\n#1 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Application.php(560): yii\\base\\Module->get('view')\n#2 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Component.php(139): yii\\base\\Application->getView()\n#3 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php(77): yii\\base\\Component->__get('view')\n#4 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\web\\ErrorHandler.php(108): yii\\di\\ServiceLocator->__get('view')\n#5 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\ErrorHandler.php(152): yii\\web\\ErrorHandler->renderException(Object(yii\\base\\InvalidConfigException))\n#6 [internal function]: yii\\base\\ErrorHandler->handleException(Object(yii\\base\\InvalidConfigException))\n#7 {main}\nPrevious exception:\nyii\\base\\InvalidConfigException: The configuration for the "params" component must contain a "class" element. in C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php:209\nStack trace:\n#0 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php(265): yii\\di\\ServiceLocator->set('params', Array)\n#1 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Component.php(180): yii\\di\\ServiceLocator->setComponents(Array)\n#2 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\BaseYii.php(557): yii\\base\\Component->__set('components', Array)\n#3 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\BaseObject.php(107): yii\\BaseYii::configure(Object(yii\\web\\Application), Array)\n#4 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Application.php(204): yii\\base\\BaseObject->__construct(Array)\n#5 C:\\xampp\\htdocs\\it.uz\\frontend\\web\\index.php(18): yii\\base\\Application->__construct(Array)\n#6 {main}
[Thu Dec 19 22:32:14.558938 2024] [php:notice] [pid 5764:tid 1848] [client 127.0.0.1:62937] An Error occurred while handling another error:\nyii\\base\\InvalidConfigException: Unknown component ID: view in C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php:139\nStack trace:\n#0 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Module.php(766): yii\\di\\ServiceLocator->get('view', true)\n#1 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Application.php(560): yii\\base\\Module->get('view')\n#2 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Component.php(139): yii\\base\\Application->getView()\n#3 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php(77): yii\\base\\Component->__get('view')\n#4 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\web\\ErrorHandler.php(108): yii\\di\\ServiceLocator->__get('view')\n#5 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\ErrorHandler.php(152): yii\\web\\ErrorHandler->renderException(Object(yii\\base\\InvalidConfigException))\n#6 [internal function]: yii\\base\\ErrorHandler->handleException(Object(yii\\base\\InvalidConfigException))\n#7 {main}\nPrevious exception:\nyii\\base\\InvalidConfigException: The configuration for the "params" component must contain a "class" element. in C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php:209\nStack trace:\n#0 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php(265): yii\\di\\ServiceLocator->set('params', Array)\n#1 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Component.php(180): yii\\di\\ServiceLocator->setComponents(Array)\n#2 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\BaseYii.php(557): yii\\base\\Component->__set('components', Array)\n#3 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\BaseObject.php(107): yii\\BaseYii::configure(Object(yii\\web\\Application), Array)\n#4 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Application.php(204): yii\\base\\BaseObject->__construct(Array)\n#5 C:\\xampp\\htdocs\\it.uz\\frontend\\web\\index.php(18): yii\\base\\Application->__construct(Array)\n#6 {main}, referer: http://it.uz/frontend/web/index.php?r=site%2Fcontact
[Thu Dec 19 22:37:50.910158 2024] [php:notice] [pid 5764:tid 1848] [client 127.0.0.1:63767] An Error occurred while handling another error:\nyii\\base\\InvalidConfigException: Unknown component ID: view in C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php:139\nStack trace:\n#0 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Module.php(766): yii\\di\\ServiceLocator->get('view', true)\n#1 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Application.php(560): yii\\base\\Module->get('view')\n#2 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Component.php(139): yii\\base\\Application->getView()\n#3 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php(77): yii\\base\\Component->__get('view')\n#4 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\web\\ErrorHandler.php(108): yii\\di\\ServiceLocator->__get('view')\n#5 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\ErrorHandler.php(152): yii\\web\\ErrorHandler->renderException(Object(yii\\base\\InvalidConfigException))\n#6 [internal function]: yii\\base\\ErrorHandler->handleException(Object(yii\\base\\InvalidConfigException))\n#7 {main}\nPrevious exception:\nyii\\base\\InvalidConfigException: The configuration for the "params" component must contain a "class" element. in C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php:209\nStack trace:\n#0 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php(265): yii\\di\\ServiceLocator->set('params', Array)\n#1 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Component.php(180): yii\\di\\ServiceLocator->setComponents(Array)\n#2 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\BaseYii.php(557): yii\\base\\Component->__set('components', Array)\n#3 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\BaseObject.php(107): yii\\BaseYii::configure(Object(yii\\web\\Application), Array)\n#4 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Application.php(204): yii\\base\\BaseObject->__construct(Array)\n#5 C:\\xampp\\htdocs\\it.uz\\frontend\\web\\index.php(18): yii\\base\\Application->__construct(Array)\n#6 {main}, referer: http://it.uz/frontend/web/index.php?r=site%2Fcontact
[Thu Dec 19 22:37:52.239649 2024] [php:notice] [pid 5764:tid 1832] [client 127.0.0.1:63768] An Error occurred while handling another error:\nyii\\base\\InvalidConfigException: Unknown component ID: view in C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php:139\nStack trace:\n#0 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Module.php(766): yii\\di\\ServiceLocator->get('view', true)\n#1 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Application.php(560): yii\\base\\Module->get('view')\n#2 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Component.php(139): yii\\base\\Application->getView()\n#3 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php(77): yii\\base\\Component->__get('view')\n#4 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\web\\ErrorHandler.php(108): yii\\di\\ServiceLocator->__get('view')\n#5 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\ErrorHandler.php(152): yii\\web\\ErrorHandler->renderException(Object(yii\\base\\InvalidConfigException))\n#6 [internal function]: yii\\base\\ErrorHandler->handleException(Object(yii\\base\\InvalidConfigException))\n#7 {main}\nPrevious exception:\nyii\\base\\InvalidConfigException: The configuration for the "params" component must contain a "class" element. in C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php:209\nStack trace:\n#0 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php(265): yii\\di\\ServiceLocator->set('params', Array)\n#1 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Component.php(180): yii\\di\\ServiceLocator->setComponents(Array)\n#2 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\BaseYii.php(557): yii\\base\\Component->__set('components', Array)\n#3 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\BaseObject.php(107): yii\\BaseYii::configure(Object(yii\\web\\Application), Array)\n#4 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Application.php(204): yii\\base\\BaseObject->__construct(Array)\n#5 C:\\xampp\\htdocs\\it.uz\\frontend\\web\\index.php(18): yii\\base\\Application->__construct(Array)\n#6 {main}
[Thu Dec 19 22:37:57.351090 2024] [php:notice] [pid 5764:tid 1848] [client 127.0.0.1:63772] An Error occurred while handling another error:\nyii\\base\\InvalidConfigException: Unknown component ID: view in C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php:139\nStack trace:\n#0 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Module.php(766): yii\\di\\ServiceLocator->get('view', true)\n#1 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Application.php(560): yii\\base\\Module->get('view')\n#2 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Component.php(139): yii\\base\\Application->getView()\n#3 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php(77): yii\\base\\Component->__get('view')\n#4 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\web\\ErrorHandler.php(108): yii\\di\\ServiceLocator->__get('view')\n#5 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\ErrorHandler.php(152): yii\\web\\ErrorHandler->renderException(Object(yii\\base\\InvalidConfigException))\n#6 [internal function]: yii\\base\\ErrorHandler->handleException(Object(yii\\base\\InvalidConfigException))\n#7 {main}\nPrevious exception:\nyii\\base\\InvalidConfigException: The configuration for the "params" component must contain a "class" element. in C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php:209\nStack trace:\n#0 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php(265): yii\\di\\ServiceLocator->set('params', Array)\n#1 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Component.php(180): yii\\di\\ServiceLocator->setComponents(Array)\n#2 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\BaseYii.php(557): yii\\base\\Component->__set('components', Array)\n#3 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\BaseObject.php(107): yii\\BaseYii::configure(Object(yii\\web\\Application), Array)\n#4 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Application.php(204): yii\\base\\BaseObject->__construct(Array)\n#5 C:\\xampp\\htdocs\\it.uz\\frontend\\web\\index.php(18): yii\\base\\Application->__construct(Array)\n#6 {main}
[Thu Dec 19 22:38:01.147665 2024] [php:notice] [pid 5764:tid 1832] [client 127.0.0.1:63787] An Error occurred while handling another error:\nyii\\base\\InvalidConfigException: Unknown component ID: view in C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php:139\nStack trace:\n#0 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Module.php(766): yii\\di\\ServiceLocator->get('view', true)\n#1 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Application.php(560): yii\\base\\Module->get('view')\n#2 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Component.php(139): yii\\base\\Application->getView()\n#3 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php(77): yii\\base\\Component->__get('view')\n#4 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\web\\ErrorHandler.php(108): yii\\di\\ServiceLocator->__get('view')\n#5 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\ErrorHandler.php(152): yii\\web\\ErrorHandler->renderException(Object(yii\\base\\InvalidConfigException))\n#6 [internal function]: yii\\base\\ErrorHandler->handleException(Object(yii\\base\\InvalidConfigException))\n#7 {main}\nPrevious exception:\nyii\\base\\InvalidConfigException: The configuration for the "params" component must contain a "class" element. in C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php:209\nStack trace:\n#0 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php(265): yii\\di\\ServiceLocator->set('params', Array)\n#1 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Component.php(180): yii\\di\\ServiceLocator->setComponents(Array)\n#2 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\BaseYii.php(557): yii\\base\\Component->__set('components', Array)\n#3 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\BaseObject.php(107): yii\\BaseYii::configure(Object(yii\\web\\Application), Array)\n#4 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Application.php(204): yii\\base\\BaseObject->__construct(Array)\n#5 C:\\xampp\\htdocs\\it.uz\\frontend\\web\\index.php(18): yii\\base\\Application->__construct(Array)\n#6 {main}
[Thu Dec 19 22:38:02.346811 2024] [php:notice] [pid 5764:tid 1832] [client 127.0.0.1:63797] An Error occurred while handling another error:\nyii\\base\\InvalidConfigException: Unknown component ID: view in C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php:139\nStack trace:\n#0 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Module.php(766): yii\\di\\ServiceLocator->get('view', true)\n#1 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Application.php(560): yii\\base\\Module->get('view')\n#2 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Component.php(139): yii\\base\\Application->getView()\n#3 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php(77): yii\\base\\Component->__get('view')\n#4 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\web\\ErrorHandler.php(108): yii\\di\\ServiceLocator->__get('view')\n#5 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\ErrorHandler.php(152): yii\\web\\ErrorHandler->renderException(Object(yii\\base\\InvalidConfigException))\n#6 [internal function]: yii\\base\\ErrorHandler->handleException(Object(yii\\base\\InvalidConfigException))\n#7 {main}\nPrevious exception:\nyii\\base\\InvalidConfigException: The configuration for the "params" component must contain a "class" element. in C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php:209\nStack trace:\n#0 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php(265): yii\\di\\ServiceLocator->set('params', Array)\n#1 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Component.php(180): yii\\di\\ServiceLocator->setComponents(Array)\n#2 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\BaseYii.php(557): yii\\base\\Component->__set('components', Array)\n#3 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\BaseObject.php(107): yii\\BaseYii::configure(Object(yii\\web\\Application), Array)\n#4 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Application.php(204): yii\\base\\BaseObject->__construct(Array)\n#5 C:\\xampp\\htdocs\\it.uz\\frontend\\web\\index.php(18): yii\\base\\Application->__construct(Array)\n#6 {main}
[Thu Dec 19 22:41:58.150071 2024] [php:notice] [pid 5764:tid 1848] [client 127.0.0.1:64213] An Error occurred while handling another error:\nyii\\base\\InvalidConfigException: Unknown component ID: view in C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php:139\nStack trace:\n#0 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Module.php(766): yii\\di\\ServiceLocator->get('view', true)\n#1 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Application.php(560): yii\\base\\Module->get('view')\n#2 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Component.php(139): yii\\base\\Application->getView()\n#3 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php(77): yii\\base\\Component->__get('view')\n#4 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\web\\ErrorHandler.php(108): yii\\di\\ServiceLocator->__get('view')\n#5 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\ErrorHandler.php(152): yii\\web\\ErrorHandler->renderException(Object(yii\\base\\InvalidConfigException))\n#6 [internal function]: yii\\base\\ErrorHandler->handleException(Object(yii\\base\\InvalidConfigException))\n#7 {main}\nPrevious exception:\nyii\\base\\InvalidConfigException: The configuration for the "params" component must contain a "class" element. in C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php:209\nStack trace:\n#0 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php(265): yii\\di\\ServiceLocator->set('params', Array)\n#1 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Component.php(180): yii\\di\\ServiceLocator->setComponents(Array)\n#2 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\BaseYii.php(557): yii\\base\\Component->__set('components', Array)\n#3 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\BaseObject.php(107): yii\\BaseYii::configure(Object(yii\\web\\Application), Array)\n#4 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Application.php(204): yii\\base\\BaseObject->__construct(Array)\n#5 C:\\xampp\\htdocs\\it.uz\\frontend\\web\\index.php(18): yii\\base\\Application->__construct(Array)\n#6 {main}
[Thu Dec 19 22:51:07.456661 2024] [php:notice] [pid 5764:tid 1832] [client 127.0.0.1:65440] An Error occurred while handling another error:\nyii\\base\\InvalidConfigException: Unknown component ID: view in C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php:139\nStack trace:\n#0 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Module.php(766): yii\\di\\ServiceLocator->get('view', true)\n#1 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Application.php(560): yii\\base\\Module->get('view')\n#2 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Component.php(139): yii\\base\\Application->getView()\n#3 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php(77): yii\\base\\Component->__get('view')\n#4 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\web\\ErrorHandler.php(108): yii\\di\\ServiceLocator->__get('view')\n#5 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\ErrorHandler.php(152): yii\\web\\ErrorHandler->renderException(Object(yii\\base\\InvalidConfigException))\n#6 [internal function]: yii\\base\\ErrorHandler->handleException(Object(yii\\base\\InvalidConfigException))\n#7 {main}\nPrevious exception:\nyii\\base\\InvalidConfigException: The configuration for the "params" component must contain a "class" element. in C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php:209\nStack trace:\n#0 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php(265): yii\\di\\ServiceLocator->set('params', Array)\n#1 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Component.php(180): yii\\di\\ServiceLocator->setComponents(Array)\n#2 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\BaseYii.php(557): yii\\base\\Component->__set('components', Array)\n#3 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\BaseObject.php(107): yii\\BaseYii::configure(Object(yii\\web\\Application), Array)\n#4 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Application.php(204): yii\\base\\BaseObject->__construct(Array)\n#5 C:\\xampp\\htdocs\\it.uz\\frontend\\web\\index.php(18): yii\\base\\Application->__construct(Array)\n#6 {main}
[Thu Dec 19 22:51:15.981619 2024] [php:notice] [pid 5764:tid 1848] [client 127.0.0.1:65441] An Error occurred while handling another error:\nyii\\base\\InvalidConfigException: Unknown component ID: view in C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php:139\nStack trace:\n#0 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Module.php(766): yii\\di\\ServiceLocator->get('view', true)\n#1 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Application.php(560): yii\\base\\Module->get('view')\n#2 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Component.php(139): yii\\base\\Application->getView()\n#3 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php(77): yii\\base\\Component->__get('view')\n#4 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\web\\ErrorHandler.php(108): yii\\di\\ServiceLocator->__get('view')\n#5 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\ErrorHandler.php(152): yii\\web\\ErrorHandler->renderException(Object(yii\\base\\InvalidConfigException))\n#6 [internal function]: yii\\base\\ErrorHandler->handleException(Object(yii\\base\\InvalidConfigException))\n#7 {main}\nPrevious exception:\nyii\\base\\InvalidConfigException: The configuration for the "params" component must contain a "class" element. in C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php:209\nStack trace:\n#0 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php(265): yii\\di\\ServiceLocator->set('params', Array)\n#1 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Component.php(180): yii\\di\\ServiceLocator->setComponents(Array)\n#2 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\BaseYii.php(557): yii\\base\\Component->__set('components', Array)\n#3 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\BaseObject.php(107): yii\\BaseYii::configure(Object(yii\\web\\Application), Array)\n#4 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Application.php(204): yii\\base\\BaseObject->__construct(Array)\n#5 C:\\xampp\\htdocs\\it.uz\\frontend\\web\\index.php(18): yii\\base\\Application->__construct(Array)\n#6 {main}
[Thu Dec 19 22:51:17.769634 2024] [php:notice] [pid 5764:tid 1832] [client 127.0.0.1:65460] An Error occurred while handling another error:\nyii\\base\\InvalidConfigException: Unknown component ID: view in C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php:139\nStack trace:\n#0 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Module.php(766): yii\\di\\ServiceLocator->get('view', true)\n#1 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Application.php(560): yii\\base\\Module->get('view')\n#2 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Component.php(139): yii\\base\\Application->getView()\n#3 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php(77): yii\\base\\Component->__get('view')\n#4 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\web\\ErrorHandler.php(108): yii\\di\\ServiceLocator->__get('view')\n#5 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\ErrorHandler.php(152): yii\\web\\ErrorHandler->renderException(Object(yii\\base\\InvalidConfigException))\n#6 [internal function]: yii\\base\\ErrorHandler->handleException(Object(yii\\base\\InvalidConfigException))\n#7 {main}\nPrevious exception:\nyii\\base\\InvalidConfigException: The configuration for the "params" component must contain a "class" element. in C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php:209\nStack trace:\n#0 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php(265): yii\\di\\ServiceLocator->set('params', Array)\n#1 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Component.php(180): yii\\di\\ServiceLocator->setComponents(Array)\n#2 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\BaseYii.php(557): yii\\base\\Component->__set('components', Array)\n#3 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\BaseObject.php(107): yii\\BaseYii::configure(Object(yii\\web\\Application), Array)\n#4 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Application.php(204): yii\\base\\BaseObject->__construct(Array)\n#5 C:\\xampp\\htdocs\\it.uz\\frontend\\web\\index.php(18): yii\\base\\Application->__construct(Array)\n#6 {main}
[Thu Dec 19 22:51:24.623945 2024] [php:notice] [pid 5764:tid 1848] [client 127.0.0.1:65465] An Error occurred while handling another error:\nyii\\base\\InvalidConfigException: Unknown component ID: view in C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php:139\nStack trace:\n#0 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Module.php(766): yii\\di\\ServiceLocator->get('view', true)\n#1 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Application.php(560): yii\\base\\Module->get('view')\n#2 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Component.php(139): yii\\base\\Application->getView()\n#3 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php(77): yii\\base\\Component->__get('view')\n#4 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\web\\ErrorHandler.php(108): yii\\di\\ServiceLocator->__get('view')\n#5 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\ErrorHandler.php(152): yii\\web\\ErrorHandler->renderException(Object(yii\\base\\InvalidConfigException))\n#6 [internal function]: yii\\base\\ErrorHandler->handleException(Object(yii\\base\\InvalidConfigException))\n#7 {main}\nPrevious exception:\nyii\\base\\InvalidConfigException: The configuration for the "params" component must contain a "class" element. in C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php:209\nStack trace:\n#0 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php(265): yii\\di\\ServiceLocator->set('params', Array)\n#1 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Component.php(180): yii\\di\\ServiceLocator->setComponents(Array)\n#2 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\BaseYii.php(557): yii\\base\\Component->__set('components', Array)\n#3 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\BaseObject.php(107): yii\\BaseYii::configure(Object(yii\\web\\Application), Array)\n#4 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Application.php(204): yii\\base\\BaseObject->__construct(Array)\n#5 C:\\xampp\\htdocs\\it.uz\\frontend\\web\\index.php(18): yii\\base\\Application->__construct(Array)\n#6 {main}
[Thu Dec 19 22:51:32.299366 2024] [php:notice] [pid 5764:tid 1848] [client ::1:65509] An Error occurred while handling another error:\nyii\\base\\InvalidConfigException: Unknown component ID: view in C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php:139\nStack trace:\n#0 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Module.php(766): yii\\di\\ServiceLocator->get('view', true)\n#1 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Application.php(560): yii\\base\\Module->get('view')\n#2 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Component.php(139): yii\\base\\Application->getView()\n#3 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php(77): yii\\base\\Component->__get('view')\n#4 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\web\\ErrorHandler.php(108): yii\\di\\ServiceLocator->__get('view')\n#5 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\ErrorHandler.php(152): yii\\web\\ErrorHandler->renderException(Object(yii\\base\\InvalidConfigException))\n#6 [internal function]: yii\\base\\ErrorHandler->handleException(Object(yii\\base\\InvalidConfigException))\n#7 {main}\nPrevious exception:\nyii\\base\\InvalidConfigException: The configuration for the "params" component must contain a "class" element. in C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php:209\nStack trace:\n#0 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\di\\ServiceLocator.php(265): yii\\di\\ServiceLocator->set('params', Array)\n#1 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Component.php(180): yii\\di\\ServiceLocator->setComponents(Array)\n#2 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\BaseYii.php(557): yii\\base\\Component->__set('components', Array)\n#3 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\BaseObject.php(107): yii\\BaseYii::configure(Object(yii\\web\\Application), Array)\n#4 C:\\xampp\\htdocs\\it.uz\\vendor\\yiisoft\\yii2\\base\\Application.php(204): yii\\base\\BaseObject->__construct(Array)\n#5 C:\\xampp\\htdocs\\it.uz\\frontend\\web\\index.php(18): yii\\base\\Application->__construct(Array)\n#6 {main}
